In [2]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [10]:
ar1=np.array([[4,6],[1,2]])
ar2=np.array([[2,3],[7,5]])
ar3=ar1*ar2

In [11]:
print(ar1)
print(ar2)
print(ar3)

[[4 6]
 [1 2]]
[[2 3]
 [7 5]]
[[ 8 18]
 [ 7 10]]


In [12]:
ar4=np.matmul(ar1,ar2)
print(ar4)

[[50 42]
 [16 13]]


In [15]:
ar5=np.random.random((4,5))
print(ar5)

[[0.1675863  0.77117236 0.88828073 0.64580183 0.12692248]
 [0.24814237 0.51519129 0.06102084 0.7546006  0.56583568]
 [0.71531652 0.16600447 0.15083629 0.07008369 0.73095605]
 [0.97986596 0.21246682 0.60221045 0.84619866 0.36899073]]


In [16]:
temp = np.random.randint(1,20, 10)

In [17]:
print(temp)

[ 9  3  5 12  2  7 12  8 19 18]


In [20]:
print(np.sort(temp))

[ 2  3  5  7  8  9 12 12 18 19]


In [21]:
temp = np.random.randint(1,20, 10)

In [22]:
temp

array([12,  4, 15, 11,  9, 10, 19, 11,  3,  2])

In [27]:
np.flip(temp)

array([ 2,  3, 11, 19, 10,  9, 11, 15,  4, 12])

In [29]:
print(temp.T)

[12  4 15 11  9 10 19 11  3  2]


In [30]:
ar1=np.array([[4,6],[1,2]])
ar2=np.array([[2,3],[7,5]])
print(ar1)
print(ar1.T)

[[4 6]
 [1 2]]
[[4 1]
 [6 2]]


In [31]:
print(np.where(temp==15))

(array([2]),)


In [32]:
print(np.where(temp%2==0))

(array([0, 1, 5, 9]),)


In [33]:
print(np.square(temp))

[144  16 225 121  81 100 361 121   9   4]


In [34]:
temp.size

10

In [36]:
temp.shape

(10,)

In [39]:
y=[10,13,6,76,34,6,87,65]
y=np.array(y)
y_pred=[15,21,9,43,5,76,70,64]
y_prd=np.array(y_pred)
n=y.size
error=1/n*np.sum(np.square(y_pred-y))
print(error)

902.25


In [40]:
print(np.std(y))

31.70345998467675


In [42]:
np.mean(y)

37.125

In [43]:
def CalculateMean(x):
    m=sum(x)/x.size
    return m

In [46]:
def CalculateStd(x):
    std=np.sqrt(np.sum((x-CalculateMean(x))**2)/x.size)
    return std

In [47]:
CalculateStd(y)

31.70345998467675