In [1]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
a=np.array([34,545,65,23,65,756])

In [4]:
print(a)

[ 34 545  65  23  65 756]


In [5]:
print(a.ndim)

1


In [6]:
arr_2d=np.array([[34,65,76,3],[5,8,3,6]])

In [7]:
print(arr_2d)

[[34 65 76  3]
 [ 5  8  3  6]]


In [8]:
print(arr_2d.ndim)

2


In [9]:
a.shape

(6,)

In [10]:
arr_2d.shape

(2, 4)

In [11]:
arr_2d.size

8

In [12]:
type(arr_2d)

numpy.ndarray

In [13]:
x="abc"
type(x)

str

In [14]:
arr_2d.dtype

dtype('int64')

In [15]:
arr_3d=np.array([[[1,4,6],[5,9,5]],[[65,9,2],[2,895,6]]])
print(arr_3d)

[[[  1   4   6]
  [  5   9   5]]

 [[ 65   9   2]
  [  2 895   6]]]


In [16]:
arr_3d.ndim

3

In [17]:
arr_3d.shape

(2, 2, 3)

In [23]:
a=np.array([34,545,65,23,65,756])
print(a[4])
print(a[-2])

65
65


In [24]:
arr_2d=np.array([[34,65,76,3],[5,8,3,6]])

In [26]:
print(arr_2d)
print(arr_2d[1,1])

[[34 65 76  3]
 [ 5  8  3  6]]
8


In [27]:
arr_3d=np.array([[[1,4,6],[5,9,5]],[[65,9,2],[2,895,6]]])
print(arr_3d)

[[[  1   4   6]
  [  5   9   5]]

 [[ 65   9   2]
  [  2 895   6]]]


In [28]:
print(arr_3d[1,0,2])

2


In [29]:
print(arr_2d[1,2]+arr_2d[0,1])

68


In [30]:
print(a[1:4])

[545  65  23]


In [31]:
a=np.array([34,545,65,23,65,756,4,54,65,7,45])
print(a[1:8:1])
print(a[1:8:2])

[545  65  23  65 756   4  54]
[545  23 756  54]


In [32]:
print(a[:])

[ 34 545  65  23  65 756   4  54  65   7  45]


In [33]:
print(a[3:])

[ 23  65 756   4  54  65   7  45]


In [35]:
print(a[:5])

[ 34 545  65  23  65]


In [36]:
b=a[:5]

In [37]:
print(b)

[ 34 545  65  23  65]


In [38]:
arr_2d=np.array([[34,65,76,3],[5,8,3,6],[35,58,23,76]])
print(arr_2d)

[[34 65 76  3]
 [ 5  8  3  6]
 [35 58 23 76]]


In [39]:
print(arr_2d[:,0:2])

[[34 65]
 [ 5  8]
 [35 58]]


In [40]:
print(arr_2d[2,0:2])

[35 58]


In [41]:
print(arr_2d[2,:])

[35 58 23 76]


In [44]:
nm=np.array(["ali","uzma","farhan"],dtype='S')
type(nm)

numpy.ndarray

In [45]:
print(nm.dtype)

|S6


In [47]:
nm=np.array([34,534,54],dtype='S')
print(nm.dtype)


|S3


In [48]:
print(nm)

[b'34' b'534' b'54']


In [49]:
arr=nm.astype(int)

In [50]:
print(arr)

[ 34 534  54]


In [52]:
arr1=np.array([43,-765,0,34,0,43])
newarr=arr1.astype(bool)
print(newarr)

[ True  True False  True False  True]


In [55]:
a1=np.array([43,54,7])
a2=np.array([47,97,2])
a3=a1+a2
print(a3)

[ 90 151   9]
