In [1]:
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
a=np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a[0,2]=7
print(a)

[[1. 1. 7. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
b=np.full((3,4),5)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [6]:
c=np.full((3,4),5,dtype='complex')
print(c)

[[5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j]
 [5.+0.j 5.+0.j 5.+0.j 5.+0.j]]


In [11]:
d=np.random.random((4,6))
print(d)

[[0.34564443 0.08144553 0.0503902  0.16608061 0.77422463 0.42409045]
 [0.94640769 0.90177174 0.11373066 0.35391649 0.92765197 0.19571455]
 [0.26453677 0.8752853  0.03897944 0.41655264 0.86903782 0.83499322]
 [0.3659398  0.68925691 0.0965893  0.45434247 0.83551082 0.3272306 ]]


In [18]:
x=np.zeros((1,5))
print(x)

[[0. 0. 0. 0. 0.]]


In [17]:
x[0,1]=67
x[0,0]=54
x[0,2]=546
x[0,3]=13
x[0,4]=76
print(x)

[[ 54.  67. 546.  13.  76.]]


In [20]:
i=0
while i<5:
    x[0,i] =input('Enter any value:')
    i=i+1
print(x)

Enter any value:76
Enter any value:34
Enter any value:98
Enter any value:231
Enter any value:876
[[ 76.  34.  98. 231. 876.]]


In [21]:
y=np.zeros((4,3))
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
x=np.array([[3,6,3],[4,5,8]])
print(x)
z=x*2
print(z)

[[3 6 3]
 [4 5 8]]
[[ 6 12  6]
 [ 8 10 16]]


In [28]:
ar1=np.array([[43,6,4,2],[5,7,24,22]])
ar2=np.array([[3,2,5,27],[5,16,14,5]])
ar3=ar1+ar2
print(ar1)
print(ar2)
print(ar3)

[[43  6  4  2]
 [ 5  7 24 22]]
[[ 3  2  5 27]
 [ 5 16 14  5]]
[[46  8  9 29]
 [10 23 38 27]]


In [24]:
ar4=ar1*ar2
print(ar4)

[[129  12  20  54]
 [ 25 112 336 264]]


In [30]:
print(ar4.min())

12


In [31]:
print(ar4.max())

336


In [32]:
print(ar4.sum())

952


In [33]:
ar4.min(axis=0)

array([25, 12, 20, 54])

In [34]:
ar4.min(axis=1)

array([12, 25])

In [35]:
ar4.sum(axis=1)

array([215, 737])

In [36]:
ar5=np.array([5,4,6,6,2,4,5,6,1,3,3,6])

In [37]:
np.unique(ar5)

array([1, 2, 3, 4, 5, 6])

In [38]:
v,i=np.unique(ar5,return_index=True)
print(v,i)

[1 2 3 4 5 6] [8 4 9 1 0 2]


In [44]:
v,i,c=np.unique(ar5,return_index=True,return_counts=True)
print(v,i,c)

[1 2 3 4 5 6] [8 4 9 1 0 2] [1 1 2 2 2 4]
